run:
  # Timeout for analysis
  timeout: 5m
  # Target Go version
  go: "1.24"
  # Include test files
  tests: true

linters:
  disable-all: true
  enable:
    # Default enabled linters
    - errcheck      # Find unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Find unused constants, variables, functions and types
    # Additional linters
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - gocyclo       # Compute cyclomatic complexities
    - misspell      # Find commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - whitespace    # Detection of leading and trailing whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: false

  goimports:
    local-prefixes: github.com/keepmind9/clibot

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

# Which files/dirs to exclude
issues:
  # Exclude directories
  exclude-dirs:
    - bin
    - vendor
  # Exclude files
  exclude-files:
    - ".*\\.pb\\.go$"
  # Show only new issues
  new: false
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - govet
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
  # Independently of option `exclude` we use default exclude patterns
  exclude-use-default: false

output:
  # Formats: colored-line-number|line-number|json|tab|checkstyle|code-climate
  formats:
    - format: colored-line-number
  # Sort results by: filepath, line and column
  sort-results: true
